### ISSUE TITLE
Iteration is broken in Set in 0.2.2

### ISSUE THREAD

**Issue by aalba6675** [etingof/pyasn1#19]
Reproducer Version 0.2.2

>>> from pyasn1.type import univ
>>> my_set = univ.Set()
>>> 
>>> i1 = univ.Integer(123)
>>> i2 = univ.Integer(456)
>>> my_set[0] = i1
>>> my_set[1] = i2
>>> for k in abc:
...     print(k)
## and nothing happens

In 0.1.9:
>>> from pyasn1.type import univ
>>> my_set = univ.Set()
>>> 
>>> i1 = univ.Integer(123)
>>> i1 = univ.Integer(123)
>>> i2 = univ.Integer(456)
>>> my_set[0] = i1
>>> my_set[1] = i2
>>> for k in abc:
...     print(k)
... 
123
456

**Comment by etingof** [comment]
Thank you for your report!

This is, unfortunately, a breaking API change (as noted in [change log](https://github.com/etingof/pyasn1/blob/master/CHANGES.rst)) aimed at adding iterator protocol support to ASN.1 SEQUENCE/SET types.

Since pyasn1 0.2.x, iteration over Set/Sequence yields field names (as opposed to field values), as it used to be in pyasn1 0.1.x. That way Sequence/Set becomes much like Python dictionaries, you could use them interchangeably.

You could iterate over values by way of `.values()` method e.g. `abc.values()`. Or, if you need pyasn1 0.1.x compatibility, I'd propose something like `[abc[i] for i in len(abc)]` -- that should work for all pyasn1 versions.

Does it make sense?

**Comment by aalba6675** [comment]
Is it 0.2.x bug if  values() iteration is also not working?

Reproducer:
Iterate over third component 'bagAttributes'

class SafeBag(univ.Sequence):
    componentType = namedtype.NamedTypes(
        namedtype.NamedType('bagId', univ.ObjectIdentifier()),
        namedtype.NamedType('bagValue', univ.Any().subtype(explicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 0))),
        namedtype.OptionalNamedType('bagAttributes', univ.SetOf())
        )

I get immediate StopIteration while creating a list works.
Trying both methods:

a. iteration over values() is not working : 
>>> print (next(k[1].values()))
StopIteration

But list comprehension is working:
>>> print( [ k[1][x] for x in range(len(k[1])) ] )
[ObjectIdentifier('1.2.840.113549.1.9.22.1')]

**Comment by aalba6675** [comment]
Could you explain a bit about "field names": I am using a simplified representation of the real ASN.1:

     bagAttributes  SET OF PKCS12Attribute OPTIONAL

 what would be the field names expected?

SafeBag ::= SEQUENCE {
     bagId          BAG-TYPE.&id ({PKCS12BagSet})
     bagValue       [0] EXPLICIT BAG-TYPE.&Type({PKCS12BagSet}{@bagId}),
     bagAttributes  SET OF PKCS12Attribute OPTIONAL
 }

 PKCS12Attribute ::= SEQUENCE {
     attrId      ATTRIBUTE.&id ({PKCS12AttrSet}),
     attrValues  SET OF ATTRIBUTE.&Type ({PKCS12AttrSet}{@attrId})
 } -- This type is compatible with the X.500 type 'Attribute'

 PKCS12AttrSet ATTRIBUTE ::= {
     friendlyName | -- from PKCS #9 [23]
     localKeyId,    -- from PKCS #9
     ... -- Other attributes are allowed
 }

**Comment by aalba6675** [comment]
Thanks - that worked (creating the list).
