### ISSUE TITLE
Wrong constraint verification

### ISSUE THREAD

**Issue by Danfocus** [etingof/pyasn1#20]
Constraints (eg ValueSizeConstraint) ignores multibyte encodings

How to reproduce:
```
from pyasn1.type import char, constraint

char.UTF8String("ф").subtype(subtypeSpec=constraint.ValueSizeConstraint(1, 1))
```
```
>>> 'ф'.encode('utf-8')
b'\xd1\x84'
```

**Comment by etingof** [comment]
Thank you for your report!

Here's a [quick fix](https://github.com/etingof/pyasn1/tree/multibyte-chars-constraints) for you to try out. I'm still working on adding tests and looking for possible corner cases.

**Comment by etingof** [comment]
It turned out that it's better to have character types holding unicode contents (as opposed to serialized octet stream) so that all duck-typing features would work out-of-the-box for character types. I've updated the [branch](https://github.com/etingof/pyasn1/tree/multibyte-chars-constraints) I'm tackling this problem in.

**Comment by Danfocus** [comment]
Great!
Thank you.

**Comment by etingof** [comment]
Merged to master. Please raise an issue in case of any troubles.
